
package bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioAnulacionDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.AnulacionDocumentoAjuste")
    @ResponseWrapper(localName = "anulacionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.AnulacionDocumentoAjusteResponse")
    public RespuestaRecepcion anulacionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioAnulacionDocumentoAjuste", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionDocumentoAjuste);

    /**
     * 
     * @param solicitudServicioReversionAnulacionDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "reversionAnulacionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.ReversionAnulacionDocumentoAjuste")
    @ResponseWrapper(localName = "reversionAnulacionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.ReversionAnulacionDocumentoAjusteResponse")
    public RespuestaRecepcion reversionAnulacionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioReversionAnulacionDocumentoAjuste", targetNamespace = "")
        SolicitudReversionAnulacion solicitudServicioReversionAnulacionDocumentoAjuste);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RecepcionDocumentoAjuste")
    @ResponseWrapper(localName = "recepcionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RecepcionDocumentoAjusteResponse")
    public RespuestaRecepcion recepcionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioRecepcionDocumentoAjuste", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionDocumentoAjuste);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.VerificacionEstadoDocumentoAjuste")
    @ResponseWrapper(localName = "verificacionEstadoDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.documento.ajuste.VerificacionEstadoDocumentoAjusteResponse")
    public RespuestaRecepcion verificacionEstadoDocumentoAjuste(
        @WebParam(name = "SolicitudServicioVerificacionEstadoDocumentoAjuste", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoDocumentoAjuste);

}
