
package bo.gob.impuestos.siat.api.servicio.facturacion.electronica;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioRecepcionPaquete
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionPaqueteFactura")
    @ResponseWrapper(localName = "recepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion recepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioRecepcionPaquete", targetNamespace = "")
        SolicitudRecepcionPaquete solicitudServicioRecepcionPaquete);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionFactura
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionFactura")
    @ResponseWrapper(localName = "recepcionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionFacturaResponse")
    public RespuestaRecepcion recepcionFactura(
        @WebParam(name = "SolicitudServicioRecepcionFactura", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionFactura);

    /**
     * 
     * @param solicitudServicioReversionAnulacionFactura
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "reversionAnulacionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ReversionAnulacionFactura")
    @ResponseWrapper(localName = "reversionAnulacionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ReversionAnulacionFacturaResponse")
    public RespuestaRecepcion reversionAnulacionFactura(
        @WebParam(name = "SolicitudServicioReversionAnulacionFactura", targetNamespace = "")
        SolicitudReversionAnulacion solicitudServicioReversionAnulacionFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionMasiva
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ValidacionRecepcionMasivaFactura")
    @ResponseWrapper(localName = "validacionRecepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ValidacionRecepcionMasivaFacturaResponse")
    public RespuestaRecepcion validacionRecepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionMasiva", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioRecepcionMasiva
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionMasivaFactura")
    @ResponseWrapper(localName = "recepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionMasivaFacturaResponse")
    public RespuestaRecepcion recepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioRecepcionMasiva", targetNamespace = "")
        SolicitudRecepcionMasiva solicitudServicioRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoFactura
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.VerificacionEstadoFactura")
    @ResponseWrapper(localName = "verificacionEstadoFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.VerificacionEstadoFacturaResponse")
    public RespuestaRecepcion verificacionEstadoFactura(
        @WebParam(name = "SolicitudServicioVerificacionEstadoFactura", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionPaquete
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ValidacionRecepcionPaqueteFactura")
    @ResponseWrapper(localName = "validacionRecepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.ValidacionRecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion validacionRecepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionPaquete", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionPaquete);

    /**
     * 
     * @param solicitudServicioAnulacionFactura
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.AnulacionFactura")
    @ResponseWrapper(localName = "anulacionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.AnulacionFacturaResponse")
    public RespuestaRecepcion anulacionFactura(
        @WebParam(name = "SolicitudServicioAnulacionFactura", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionFactura);

    /**
     * 
     * @param solicitudRecepcionSuministroAnexos
     * @return
     *     returns bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaRecepcionAnexos", targetNamespace = "")
    @RequestWrapper(localName = "recepcionAnexosSuministroEnergia", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionAnexosSuministroEnergia")
    @ResponseWrapper(localName = "recepcionAnexosSuministroEnergiaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.siat.api.servicio.facturacion.electronica.RecepcionAnexosSuministroEnergiaResponse")
    public RespuestaRecepcion recepcionAnexosSuministroEnergia(
        @WebParam(name = "SolicitudRecepcionSuministroAnexos", targetNamespace = "")
        SolicitudRecepcionAnexosSuministroEnergia solicitudRecepcionSuministroAnexos);

}
